[versions]
# libraries
junit = "4.13.2"
junit5 = "5.12.2"

# plugins
changelog = "2.2.1"
intelliJPlatform = "2.5.0"
kotlin = "2.1.21"
kover = "0.9.1"
qodana = "2025.1.0"
grammarkit = "2022.3.2.2"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit5 = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit5" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
grammarkit = { id = "org.jetbrains.grammarkit", version.ref = "grammarkit" }
